In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [4]:
df_cast=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\cleaned_cast.csv")
df_cast

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_26488\3052720672.py:1: SyntaxWarning: invalid escape sequence '\G'
  df_cast=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\cleaned_cast.csv")

,movie_id,person_id,actor_name,character_name,cast_order
0,157336,10297,Matthew McConaughey,Cooper,0
1,157336,1813,Anne Hathaway,Brand,1
2,157336,3895,Michael Caine,Professor Brand,2
3,157336,83002,Jessica Chastain,Murph,3
4,157336,1893,Casey Affleck,Tom,4
...,...,...,...,...,...
24897,19901,77496,Vince Colosimo,Christopher Caruso,5
24898,19901,33182,Jay Laga'aia,Senator Turner,6
24899,19901,76068,Michael Dorman,Frankie Dalton,7
24900,19901,1121519,Harriet Minto-Day,Lisa Barrett,8
24901,19901,61911,Tiffany Lamb,News Reader,9

In [5]:
df_crew=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_crew.csv")
df_crew

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_26488\1932302037.py:1: SyntaxWarning: invalid escape sequence '\G'
  df_crew=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_crew.csv")

      movie_id  person_id        person_name         job department
0       157336        527     Jonathan Nolan      Writer    Writing
1       157336        525  Christopher Nolan      Writer    Writing
2       157336        525  Christopher Nolan    Director  Directing
3        27205        525  Christopher Nolan      Writer    Writing
4        27205        525  Christopher Nolan    Director  Directing
...        ...        ...                ...         ...        ...
7284      7461      52680         Barry Levy      Writer    Writing
7285     19901      56501    Michael Spierig    Director  Directing
7286     19901      56502      Peter Spierig    Director  Directing
7287     19901      56501    Michael Spierig  Screenplay    Writing
7288     19901      56502      Peter Spierig  Screenplay    Writing

[7289 rows x 5 columns]

In [6]:
df_genres=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_genres.csv")
df_genres

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_26488\386929535.py:1: SyntaxWarning: invalid escape sequence '\G'
  df_genres=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_genres.csv")

    genre_id       genre_name
0         28           Action
1         12        Adventure
2         16        Animation
3         35           Comedy
4         80            Crime
5         99      Documentary
6         18            Drama
7      10751           Family
8         14          Fantasy
9         36          History
10        27           Horror
11     10402            Music
12      9648          Mystery
13     10749          Romance
14       878  Science Fiction
15     10770         TV Movie
16        53         Thriller
17     10752              War
18        37          Western

In [7]:
df_movie_genres=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_movie_genres.csv")
df_movie_genres

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_26488\4032871070.py:1: SyntaxWarning: invalid escape sequence '\G'
  df_movie_genres=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_movie_genres.csv")

      movie_id  genre_id
0       157336        12
1       157336        18
2       157336       878
3        27205        28
4        27205       878
...        ...       ...
6873      7461        53
6874      7461        80
6875     19901        28
6876     19901        14
6877     19901       878

[6878 rows x 2 columns]

In [8]:
df_movie_keywords=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_movie_keywords.csv")
df_movie_keywords

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_26488\3253092594.py:1: SyntaxWarning: invalid escape sequence '\G'
  df_movie_keywords=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_movie_keywords.csv")

       movie_id  keyword_id                    keyword_name
0        157336        1612                      spacecraft
1        157336        4776               race against time
2        157336         310  artificial intelligence (a.i.)
3        157336        1432                            nasa
4        157336        1521                       time warp
...         ...         ...                             ...
41676     19901       34079                           death
41677     19901      160153                            dead
41678     19901      232469                    urban gothic
41679     19901      243150                   brutal deaths
41680     19901      325824                         hopeful

[41681 rows x 3 columns]

In [9]:
df_movies=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_movies.csv")
df_movies

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_26488\709494078.py:1: SyntaxWarning: invalid escape sequence '\G'
  df_movies=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_movies.csv")

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,overview,year,month,day,day_name,profit
0,157336,Interstellar,en,2014-11-05,169,1.650000e+08,7.466067e+08,73.0452,8.484,40566,The adventures of a group of explorers who mak...,2014,11,5,Wednesday,5.816067e+08
1,27205,Inception,en,2010-07-15,148,1.600000e+08,8.390306e+08,55.8497,8.400,39727,"Cobb, a skilled thief who commits corporate es...",2010,7,15,Thursday,6.790306e+08
2,24428,The Avengers,en,2012-04-25,143,2.200000e+08,1.518816e+09,72.2515,8.062,38993,When an unexpected enemy emerges and threatens...,2012,4,25,Wednesday,1.298816e+09
3,155,The Dark Knight,en,2008-07-16,152,1.850000e+08,1.004558e+09,60.5510,8.534,36255,Batman raises the stakes in his war on crime. ...,2008,7,16,Wednesday,8.195584e+08
4,19995,Avatar,en,2009-12-16,162,2.370000e+08,2.923706e+09,48.1996,7.610,34348,"In the 22nd century, a paraplegic Marine is di...",2009,12,16,Wednesday,2.686706e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2498,19901,Daybreakers,en,2010-01-06,98,2.000000e+07,5.141719e+07,6.5762,6.285,2223,"In the year 2019, a plague has transformed alm...",2010,1,6,Wednesday,3.141719e+07
2499,1368167,Date Night,en,1995-04-08,88,9.321480e+07,8.759568e+07,8.2930,7.000,1051,Phil and Claire Foster fear that their mild-ma...,1995,4,8,Saturday,-5.619119e+06
2500,1368168,Transformers,en,1987-06-27,144,1.100988e+08,2.747467e+08,6.5902,7.900,4215,Young teenager Sam Witwicky becomes involved i...,1987,6,27,Saturday,1.646479e+08
2501,1368169,The SpongeBob Movie: Sponge Out of Water,en,2000-01-28,93,3.928488e+07,5.706575e+08,11.3857,7.100,475,Evil pirate Burger Beard is in search of the f...,2000,1,28,Friday,5.313726e+08
2502,1368170,Fargo,en,2011-03-08,98,5.425747e+06,4.584468e+07,11.2271,7.900,2514,"Jerry, a small-town Minnesota car salesman is ...",2011,3,8,Tuesday,4.041893e+07

VISUALIZATION CHART 1

insights - after the year of 2000 lot of files are released

In [10]:
df_year = df_movies.groupby("year")["movie_id"].nunique().reset_index()

fig = px.line(
    df_year,
    x="year",
    y="movie_id",
    title="Number of Movies Released Each Year"
)

fig.show()

VISUALIZATION CHART 2

insights - Most of the films budget is around 1 to 50 million

In [14]:
df_budget=df_movies[df_movies["budget"] > 0]

fig = px.histogram(
    df_budget,
    x="budget",
    nbins=50,
    title="Distribution of movie budget"
)

fig.show()

VISUALIZATION CHART 3

insight-Typical movie runtime 111 minutes
        50% movie are in between the runtime of 99 to 126 minutes
        Longest movies in the dataset will be 242 minutes
        shortes movies in the dataset will be 45 minutes

In [15]:
df_runtime=df_movies[df_movies["runtime"] > 0]

fig = px.box(
    df_runtime,
    y="runtime",
    title="Distribution of movies run time"
)

fig.show()

VISUALIZATION CHART 4

insights - Genre of Drama have highest no.of movies (937)
           Genre of documentry have least no.of movies (1)

In [19]:
df_genre_count = (
    df_movie_genres
    .merge(df_genres, on="genre_id", how="left")
    .groupby("genre_name")["movie_id"]
    .nunique()
    .reset_index(name="movie_count")
)

fig = px.bar(
    df_genre_count,
    x="genre_name",
    y="movie_count",
    title="Count of Movies per Genre"
)

fig.show()

VISUALIZATION CHART 5

insights - High Budget movies secure high revenue (ex: avatar)

In [22]:
df_budget_revenue = df_movies[(df_movies["budget"] > 0) & (df_movies["revenue"] > 0)]

fig = px.scatter(
    df_budget_revenue,
    x="budget",
    y="revenue",
    trendline="ols",
    hover_name="title",
    title="Movie vs Budget",
    labels = {"budget" : "Movie budget",
              "revenue" : "Movie revenue"}
)

fig.show()

VISUALIZATION CHART 6

insights - War genre movies got the highest avg rating 
           Horror genre movies got the lowest avg rating

In [23]:
df_rating_genre = df_movie_genres.merge(
    df_genres,
    on="genre_id",
    how="left"
)


df_rating_genre = df_rating_genre.merge(
    df_movies[["movie_id", "vote_average"]],
    on="movie_id",
    how="left"
)


df_rating_genre = df_rating_genre.dropna(
    subset=["vote_average", "genre_name"]
)


df_avg_rating = (
    df_rating_genre
    .groupby("genre_name")["vote_average"]
    .mean()
    .reset_index(name="avg_rating")
    .sort_values("avg_rating")
)


fig = px.scatter(
    df_avg_rating,
    x="avg_rating",
    y="genre_name",
    title="Average Rating by Genre — Dot Plot",
    labels={
        "avg_rating": "Average Rating",
        "genre_name": "Genre"
    },
    text="avg_rating"
)

fig.update_traces(
    marker=dict(size=12),
    texttemplate="%{text:.2f}",
    textposition="middle right"
)

fig.update_layout(
    xaxis_range=[0, 10]
)

fig.show()

VISUALIZATION CHART 7

insights - Revenue and budget has strong correlation
           Budget and vote_average has strong negative correlation

In [34]:
df_corr = df_movies[
    [
        "budget",
        "revenue",
        "runtime",
        "popularity",
        "vote_average",
        "vote_count"
    ]
]

corr_matrix = df_corr.corr()

fig = px.imshow(
    corr_matrix,
    text_auto=".2f",
    color_continuous_scale="RdBu_r",
    zmin=-1,
    zmax=1,
    title="Correlation Heatmap of Movie Features"
)

fig.update_layout(
    width=800,
    height=700
)

fig.show()

VISUALIZATION CHART 8

insights - Almost all movie vote_average will be around 6 to 8

In [36]:
df_primary_genre = (
    df_movie_genres
    .drop_duplicates(subset="movie_id", keep="first")
    .merge(df_genres, on="genre_id", how="left")
    [["movie_id", "genre_name"]]
    .rename(columns={"genre_name": "primary_genre"})
)

df_pairplot = df_movies.merge(
    df_primary_genre,
    on="movie_id",
    how="left"
)

cols = [
    "budget",
    "revenue",
    "popularity",
    "vote_average",
    "primary_genre"
]

df_pairplot = df_pairplot[cols].dropna()

fig = px.scatter_matrix(
    df_pairplot,
    dimensions=[
        "budget",
        "revenue",
        "popularity",
        "vote_average"
    ],
    color="primary_genre",
    title="Movie Pairplot by Primary Genre",
    opacity=0.5
)

fig.update_traces(
    diagonal_visible=True,
    showupperhalf=False,
    marker=dict(size=5)
)

fig.show()