In [2]:
import pandas as pd

In [3]:
df_cast=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\cleaned_cast.csv")
df_cast

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_14784\3052720672.py:1: SyntaxWarning: invalid escape sequence '\G'
  df_cast=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\cleaned_cast.csv")

,movie_id,person_id,actor_name,character_name,cast_order
0,157336,10297,Matthew McConaughey,Cooper,0
1,157336,1813,Anne Hathaway,Brand,1
2,157336,3895,Michael Caine,Professor Brand,2
3,157336,83002,Jessica Chastain,Murph,3
4,157336,1893,Casey Affleck,Tom,4
...,...,...,...,...,...
24897,19901,77496,Vince Colosimo,Christopher Caruso,5
24898,19901,33182,Jay Laga'aia,Senator Turner,6
24899,19901,76068,Michael Dorman,Frankie Dalton,7
24900,19901,1121519,Harriet Minto-Day,Lisa Barrett,8
24901,19901,61911,Tiffany Lamb,News Reader,9

In [4]:
df_crew=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_crew.csv")
df_crew

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_14784\1932302037.py:1: SyntaxWarning: invalid escape sequence '\G'
  df_crew=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_crew.csv")

      movie_id  person_id        person_name         job department
0       157336        527     Jonathan Nolan      Writer    Writing
1       157336        525  Christopher Nolan      Writer    Writing
2       157336        525  Christopher Nolan    Director  Directing
3        27205        525  Christopher Nolan      Writer    Writing
4        27205        525  Christopher Nolan    Director  Directing
...        ...        ...                ...         ...        ...
7284      7461      52680         Barry Levy      Writer    Writing
7285     19901      56501    Michael Spierig    Director  Directing
7286     19901      56502      Peter Spierig    Director  Directing
7287     19901      56501    Michael Spierig  Screenplay    Writing
7288     19901      56502      Peter Spierig  Screenplay    Writing

[7289 rows x 5 columns]

In [5]:
df_genres=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_genres.csv")
df_genres

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_14784\386929535.py:1: SyntaxWarning: invalid escape sequence '\G'
  df_genres=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_genres.csv")

    genre_id       genre_name
0         28           Action
1         12        Adventure
2         16        Animation
3         35           Comedy
4         80            Crime
5         99      Documentary
6         18            Drama
7      10751           Family
8         14          Fantasy
9         36          History
10        27           Horror
11     10402            Music
12      9648          Mystery
13     10749          Romance
14       878  Science Fiction
15     10770         TV Movie
16        53         Thriller
17     10752              War
18        37          Western

In [6]:
df_movie_genres=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_movie_genres.csv")
df_movie_genres

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_14784\4032871070.py:1: SyntaxWarning: invalid escape sequence '\G'
  df_movie_genres=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_movie_genres.csv")

      movie_id  genre_id
0       157336        12
1       157336        18
2       157336       878
3        27205        28
4        27205       878
...        ...       ...
6873      7461        53
6874      7461        80
6875     19901        28
6876     19901        14
6877     19901       878

[6878 rows x 2 columns]

In [7]:
df_movie_keywords=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_movie_keywords.csv")
df_movie_keywords

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_14784\3253092594.py:1: SyntaxWarning: invalid escape sequence '\G'
  df_movie_keywords=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_movie_keywords.csv")

       movie_id  keyword_id                    keyword_name
0        157336        1612                      spacecraft
1        157336        4776               race against time
2        157336         310  artificial intelligence (a.i.)
3        157336        1432                            nasa
4        157336        1521                       time warp
...         ...         ...                             ...
41676     19901       34079                           death
41677     19901      160153                            dead
41678     19901      232469                    urban gothic
41679     19901      243150                   brutal deaths
41680     19901      325824                         hopeful

[41681 rows x 3 columns]

In [8]:
df_movies=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_movies.csv")
df_movies

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_14784\709494078.py:1: SyntaxWarning: invalid escape sequence '\G'
  df_movies=pd.read_csv("D:\GUVI\Project\Datasets\data\clean data\Cleaned_movies.csv")

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,overview,year,month,day,day_name,profit
0,157336,Interstellar,en,2014-11-05,169,1.650000e+08,7.466067e+08,73.0452,8.484,40566,The adventures of a group of explorers who mak...,2014,11,5,Wednesday,5.816067e+08
1,27205,Inception,en,2010-07-15,148,1.600000e+08,8.390306e+08,55.8497,8.400,39727,"Cobb, a skilled thief who commits corporate es...",2010,7,15,Thursday,6.790306e+08
2,24428,The Avengers,en,2012-04-25,143,2.200000e+08,1.518816e+09,72.2515,8.062,38993,When an unexpected enemy emerges and threatens...,2012,4,25,Wednesday,1.298816e+09
3,155,The Dark Knight,en,2008-07-16,152,1.850000e+08,1.004558e+09,60.5510,8.534,36255,Batman raises the stakes in his war on crime. ...,2008,7,16,Wednesday,8.195584e+08
4,19995,Avatar,en,2009-12-16,162,2.370000e+08,2.923706e+09,48.1996,7.610,34348,"In the 22nd century, a paraplegic Marine is di...",2009,12,16,Wednesday,2.686706e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2498,19901,Daybreakers,en,2010-01-06,98,2.000000e+07,5.141719e+07,6.5762,6.285,2223,"In the year 2019, a plague has transformed alm...",2010,1,6,Wednesday,3.141719e+07
2499,1368167,Date Night,en,1995-04-08,88,9.321480e+07,8.759568e+07,8.2930,7.000,1051,Phil and Claire Foster fear that their mild-ma...,1995,4,8,Saturday,-5.619119e+06
2500,1368168,Transformers,en,1987-06-27,144,1.100988e+08,2.747467e+08,6.5902,7.900,4215,Young teenager Sam Witwicky becomes involved i...,1987,6,27,Saturday,1.646479e+08
2501,1368169,The SpongeBob Movie: Sponge Out of Water,en,2000-01-28,93,3.928488e+07,5.706575e+08,11.3857,7.100,475,Evil pirate Burger Beard is in search of the f...,2000,1,28,Friday,5.313726e+08
2502,1368170,Fargo,en,2011-03-08,98,5.425747e+06,4.584468e+07,11.2271,7.900,2514,"Jerry, a small-town Minnesota car salesman is ...",2011,3,8,Tuesday,4.041893e+07

1) List the total number of unique movies, genres, cast members and crew members collected across all tables.

In [8]:
print(
    "Unique Movies:",df_movies["movie_id"].nunique(),
    "\nUnique Genres:", df_genres["genre_id"].nunique(),
    "\nUnique Cast Members:", df_cast["person_id"].nunique(),
    "\nUnique Crew Members:", df_crew["person_id"].nunique()
)

Unique Movies: 2503
Unique Genres: 19
Unique Cast Members: 11300
Unique Crew Members: 2848

In [ ]:
2) List all movies with missing or zero budget/revenue values, and decide how these 
   should be treated for the rest of the analysis.

In [15]:
df_movies.columns

Index(['movie_id', 'title', 'original_language', 'release_date', 'runtime',
       'budget', 'revenue', 'popularity', 'vote_average', 'vote_count',
       'overview', 'year', 'month', 'day', 'day_name', 'profit'],
      dtype='str')

In [10]:
df_movies[["budget","revenue"]].isna().sum()

budget      90
revenue    102
dtype: int64

In [9]:
df_movies[df_movies["budget"].isna() | df_movies["revenue"].isna()][["movie_id", "title", "budget", "revenue"]]

      movie_id                              title       budget    revenue
324     791373       Zack Snyder's Justice League   70000000.0        NaN
340     405774                           Bird Box   19800000.0        NaN
403     664413                           365 Days          NaN  9458590.0
468     466282  To All the Boys I've Loved Before          NaN        NaN
554     766507                               Prey   65000000.0        NaN
...        ...                                ...          ...        ...
2469    755566                          Day Shift  100000000.0        NaN
2471     73861                     A Serbian Film          NaN        NaN
2480     11104                  Chungking Express     160000.0        NaN
2481    500840      I'm Thinking of Ending Things          NaN        NaN
2491    868759                            Ghosted   40000000.0        NaN

[133 rows x 4 columns]

3)List the profit (revenue − budget) and return on investment for every movie that has valid budget and revenue figures.

In [19]:
df_movies["profit"]

0       5.816067e+08
1       6.790306e+08
2       1.298816e+09
3       8.195584e+08
4       2.686706e+09
            ...
2498    3.141719e+07
2499   -5.619119e+06
2500    1.646479e+08
2501    5.313726e+08
2502    4.041893e+07
Name: profit, Length: 2503, dtype: float64

In [17]:
df_movies["ROI"]=(df_movies["profit"]/df_movies["budget"])*100

In [21]:
df_movies[["title","budget","revenue","profit","ROI"]]

,title,budget,revenue,profit,ROI
0,Interstellar,1.650000e+08,7.466067e+08,5.816067e+08,352.488913
1,Inception,1.600000e+08,8.390306e+08,6.790306e+08,424.394144
2,The Avengers,2.200000e+08,1.518816e+09,1.298816e+09,590.370689
3,The Dark Knight,1.850000e+08,1.004558e+09,8.195584e+08,443.004564
4,Avatar,2.370000e+08,2.923706e+09,2.686706e+09,1133.631235
...,...,...,...,...,...
2498,Daybreakers,2.000000e+07,5.141719e+07,3.141719e+07,157.085940
2499,Date Night,9.321480e+07,8.759568e+07,-5.619119e+06,-6.028140
2500,Transformers,1.100988e+08,2.747467e+08,1.646479e+08,149.545660
2501,The SpongeBob Movie: Sponge Out of Water,3.928488e+07,5.706575e+08,5.313726e+08,1352.613653
2502,Fargo,5.425747e+06,4.584468e+07,4.041893e+07,744.946776

In [ ]:
4)List the top 15 movies by return on investment, considering only movies with a budget of at least $1 million.

In [24]:
df_movies[df_movies["budget"] >= 1000000].sort_values("ROI",ascending=False)[["title","budget","profit","ROI"]].head(15)

                                title      budget       profit           ROI
1767         Dragon Ball Super: Broly   1000000.0  124002821.0  12400.282100
535   Snow White and the Seven Dwarfs   1488423.0  183437063.0  12324.256142
1791    The Rocky Horror Picture Show   1400000.0  169781400.0  12127.242857
467                             Rocky   1000000.0  116253345.0  11625.334500
1227               Gone with the Wind   4000000.0  398352579.0   9958.814475
716                   The Jungle Book   4000000.0  374000000.0   9350.000000
635                        Cinderella   2900000.0  260700000.0   8989.655172
372                               Saw   1200000.0  102845735.0   8570.477917
719    One Hundred and One Dalmatians   3600000.0  299400000.0   8316.666667
263        E.T. the Extra-Terrestrial  10500000.0  786807407.0   7493.403876
2399         My Big Fat Greek Wedding   5000000.0  363744044.0   7274.880880
43                          Star Wars  11000000.0  764398007.0   6949.072791
274                              Jaws   7000000.0  463653000.0   6623.614286
608                         Insidious   1500000.0   98606454.0   6573.763600
569                            Grease   6000000.0  390271103.0   6504.518383

In [ ]:
5)List the number of movies released per year, and identify which year had the highest movie output in the dataset.

In [28]:
df_movies["year"].value_counts().sort_values(ascending=False).head(5)

year
2016    121
2013    110
2017    109
2014    105
2018    102
Name: count, dtype: int64

In [ ]:
6)List all movies whose runtime is a statistical outlier compared to the rest of the dataset.

In [30]:
Q1=df_movies["runtime"].quantile(0.25)
Q3=df_movies["runtime"].quantile(0.75)

IQR = Q3 - Q1

df_movies_runtime_outliers=df_movies[(df_movies["runtime"] < Q1 - 1.5 * IQR) | 
                                     (df_movies["runtime"] > Q3 + 1.5 * IQR) ]

df_movies_runtime_outliers[["movie_id","title","runtime"]]

      movie_id                                              title  runtime
0       157336                                       Interstellar      169
16      299534                                  Avengers: Endgame      181
18         120  The Lord of the Rings: The Fellowship of the Ring      179
19         597                                            Titanic      194
20         122      The Lord of the Rings: The Return of the King      201
21      106646                            The Wolf of Wall Street      180
28         121              The Lord of the Rings: The Two Towers      179
38         238                                      The Godfather      175
76       49051                  The Hobbit: An Unexpected Journey      169
79         497                                     The Green Mile      189
108        424                                   Schindler's List      195
110        857                                Saving Private Ryan      169
146        285           Pirates of the Caribbean: At World's End      169
152     273248                                  The Hateful Eight      188
178      76600                           Avatar: The Way of Water      192
187        240                              The Godfather Part II      202
219        111                                           Scarface      170
258     414906                                         The Batman      177
260     872585                                        Oppenheimer      181
302        197                                         Braveheart      178
324     791373                       Zack Snyder's Justice League      242
397     474350                                     It Chapter Two      169
480        254                                          King Kong      188
492        949                                               Heat      170
514     693134                                     Dune: Part Two      167
528     603692                               John Wick: Chapter 4      170
587     398978                                       The Irishman      209
589      83542                                        Cloud Atlas      172
620       3131                                  Gangs of New York      168
658        676                                       Pearl Harbor      183
733        524                                             Casino      179
829        311                        Once Upon a Time in America      229
862       2567                                        The Aviator      170
873        297                                     Meet Joe Black      178
1071    152584                          Blue Is the Warmest Color      180
1118       581                                 Dances with Wolves      181
1171     19404                        Dilwale Dulhania Le Jayenge      190
1227       770                                 Gone with the Wind      238
1270     11778                                    The Deer Hunter      183
1277       346                                      Seven Samurai      207
1304    466420                         Killers of the Flower Moon      206
1360       334                                           Magnolia      189
1378     83533                               Avatar: Fire and Ash      198
1467    615777                                            Babylon      189
1531     15121                                 The Sound of Music      174
1583      1966                                          Alexander      176
1610       947                                 Lawrence of Arabia      228
1694      8741                                  The Thin Red Line      171
1756      3175                                       Barry Lyndon      188
1774       665                                            Ben-Hur      212
1897    575265          Mission: Impossible - The Final Reckoning      170
1968      5925                                   The Great Escape      173
2034     20453                                           3 Idiots      171
2066       553                                           Dogville      178
2210       783                                             Gandhi      192
2260     10376                                 The Legend of 1900      170
2271       820                                                JFK      189
2305       967                                          Spartacus      197
2307    774752        The Guardians of the Galaxy Holiday Special       45
2447    198375                                The Garden of Words       46

In [ ]:
7) List each movie's primary genre (the first genre listed) and compare average popularity across primary genres.

In [13]:
primary_genres = (
    df_movie_genres
    .sort_values("genre_id")
    .drop_duplicates(subset="movie_id", keep="first")
    .merge(df_genres, on="genre_id", how="left")
    .merge(df_movies[["movie_id", "title", "popularity"]], on="movie_id", how="left")
)

primary_genres[["movie_id", "title", "genre_name", "popularity"]]

,movie_id,title,genre_name,popularity
0,293660,Deadpool,Adventure,29.3387
1,19995,Avatar,Adventure,48.1996
2,24428,The Avengers,Adventure,72.2515
3,27205,Inception,Adventure,55.8497
4,127380,Finding Dory,Adventure,13.2121
...,...,...,...,...
2494,899082,Harry Potter 20th Anniversary: Return to Hogwarts,Documentary,7.7262
2495,17654,District 9,Science Fiction,14.6730
2496,2666,Dark City,Science Fiction,12.8200
2497,1903,Vanilla Sky,Science Fiction,10.2997
2498,635744,Jarhead: Law of Return,War,3.2184

In [14]:
primary_genres.groupby("genre_name")["popularity"].mean().sort_values(ascending=False)

genre_name
Thriller           18.854481
Adventure          17.372862
Animation          15.234531
Horror             14.600246
Crime              14.592000
Western            13.714286
Action             13.284634
Science Fiction    12.597567
Fantasy            12.424829
Drama              11.151012
History            10.754000
Comedy             10.148475
Documentary         7.726200
War                 3.218400
Name: popularity, dtype: float64

In [ ]:
8) List the top 10 most prolific actors by number of movies, along with their average movie rating
   across those movies.

In [15]:
top_10_actors = (
    df_cast
    .merge(
        df_movies[["movie_id", "vote_average"]],
        on="movie_id",
        how="left"
    )
    .groupby(["person_id", "actor_name"])
    .agg(
        movie_count=("movie_id", "nunique"),
        avg_rating=("vote_average", "mean")
    )
    .sort_values("movie_count", ascending=False)
    .head(10)
    .reset_index()
)

print(top_10_actors)

   person_id          actor_name  movie_count  avg_rating
0       2231   Samuel L. Jackson           39    6.938692
1        287           Brad Pitt           38    7.257289
2        380      Robert De Niro           38    7.228316
3         85         Johnny Depp           37    6.856973
4         31           Tom Hanks           33    7.289758
5       5293        Willem Dafoe           32    7.114781
6       1245  Scarlett Johansson           32    7.056344
7      13240       Mark Wahlberg           32    6.630063
8        500          Tom Cruise           31    7.040613
9        192      Morgan Freeman           31    6.963742

In [ ]:
9) List any movie titles that appear more than once in the dataset, along with their release years,
   to check for duplicates or remakes.

In [10]:
duplicate_titles = df_movies[df_movies.duplicated(subset="title", keep=False)].sort_values("title")[["title", "year"]]
duplicate_titles

                          title  year
878   A Nightmare on Elm Street  1984
1928  A Nightmare on Elm Street  2010
261                     Aladdin  1992
339                     Aladdin  2019
792         Alice in Wonderland  1951
...                         ...   ...
1737                  The Thing  2011
860                Total Recall  2012
744                Total Recall  1990
252                Transformers  2007
2500               Transformers  1987

[100 rows x 2 columns]

In [ ]:
10) List movies whose popularity score and vote count don't follow the general pattern between
    the two — i.e., unusually high popularity with a low vote count, or vice versa.

In [11]:
df_movies.columns

Index(['movie_id', 'title', 'original_language', 'release_date', 'runtime',
       'budget', 'revenue', 'popularity', 'vote_average', 'vote_count',
       'overview', 'year', 'month', 'day', 'day_name', 'profit'],
      dtype='str')

In [12]:
pop_high = df_movies["popularity"].quantile(0.75)
pop_low = df_movies["popularity"].quantile(0.25)

vote_high = df_movies["vote_count"].quantile(0.75)
vote_low = df_movies["vote_count"].quantile(0.25)

unusual_movies = df_movies[((df_movies["popularity"] >= pop_high) & (df_movies["vote_count"] <= vote_low)) |
                           ((df_movies["popularity"] <= pop_low) & (df_movies["vote_count"] >= vote_high))]

In [14]:
unusual_movies[["title","popularity","vote_count"]].sort_values("popularity",ascending=False)

                              title  popularity  vote_count
2388                 Disclosure Day    394.3346        2328
2248                      Backrooms    258.4743        2483
2452               Mortal Kombat II     99.5231        2260
2295         Lee Cronin's The Mummy     79.4601        2430
2022                  The Housemaid     41.4337        2789
...                             ...         ...         ...
205              X-Men: First Class      1.2614       13680
354           X-Men: The Last Stand      1.1649       10511
322                              X2      0.8734       11013
417   The Lost World: Jurassic Park      0.8620        9356
547               Jurassic Park III      0.7820        7968

[68 rows x 3 columns]